---
title: "Excess_Mortality_Q4.qmd"
format: html
editor: visual
---

## Question 4: **For those working in groups**: Estimate excess mortality for each week for each state. Do COVID-19 deaths explain the excess mortality? - pick a good region/state to show this holds

```{r}
library(dplyr)
library(tidyverse)
library(lubridate)
library(ggrepel)
```

```{r}
dat <- readRDS('../data/dat.rds')
pre_covid <- readRDS('../data/dat_preCovid.rds')
#write.csv(pre_covid, "pre_covid.csv", row.names = FALSE)
```

#use the pre-covid data to train and test on dat

```{r}
head(pre_covid)
unique(pre_covid$mmwr_year)

View(dat)
```

```{r}
fit <- pre_covid |> lm(total_deaths ~ as.factor(state) + as.factor(mmwr_week) + as.factor(region), data = _)
summary(fit)
```

```{r}
predicted_deaths <- predict(fit, newdata = dat, se.fit = TRUE)

dat2 <- dat |>
  mutate(
    expected_deaths = predicted_deaths$fit, 
    expected_deaths_se = predicted_deaths$se.fit, 
    excess_deaths = total_deaths - expected_deaths, 
  )

View(dat2)

```

```{r}
# Reshape data for plotting

#Can provide example from wave 1 to show alignment

#For Wave 1- State doing poorly - NJ

w1_worst <- dat2 |> 
  filter(state %in% c("NJ")) |> 
  #wave 1: April 2020 - June 2020
  filter(date >= make_date(2020, 3, 15) & date <= make_date(2020, 6, 1)) |> 
  select(state, mmwr_year, mmwr_week, total_deaths, covid_deaths, excess_deaths) |>
  pivot_longer(
    cols = c(covid_deaths, excess_deaths),
    names_to = "type",
    values_to = "deaths"
  )

#For Wave 1- State doing well - AK 

w1_best <- dat2 |> 
  filter(state %in% c("AK")) |> 
  #wave 1: April 2020 - June 2020
  filter(date >= make_date(2020, 3, 15) & date <= make_date(2020, 6, 1)) |> 
  select(state, mmwr_year, mmwr_week, total_deaths, covid_deaths, excess_deaths) |>
  pivot_longer(
    cols = c(covid_deaths, excess_deaths),
    names_to = "type",
    values_to = "deaths"
  )


library(ggplot2)
ggplot(w1_worst, aes(x = mmwr_week, y = deaths, color = type, group = type)) +
  geom_line() +
  facet_wrap(~mmwr_year, scales = "free_y") +
  labs(
    title = "COVID Deaths vs Excess Deaths for NJ ",
    x = "MMWR Week",
    y = "Number of Deaths",
    color = "Type"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


ggplot(w1_best, aes(x = mmwr_week, y = deaths, color = type, group = type)) +
  geom_line() +
  facet_wrap(~mmwr_year, scales = "free_y") +
  labs(
    title = "COVID Deaths vs Excess Deaths for AK in Wave 1",
    x = "MMWR Week",
    y = "Number of Deaths",
    color = "Type"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
#For wave 2 - State doing poorly - South Dakota

w2_worst <- dat2 |> 
  filter(state %in% c("SD")) |> 
  #wave 2: October 2020 - March 2021
  filter(date >= make_date(2020, 9, 1) & date <= make_date(2021, 4, 1)) |> 
  select(state, mmwr_year, mmwr_week, total_deaths, covid_deaths, excess_deaths) |>
  pivot_longer(
    cols = c(covid_deaths, excess_deaths),
    names_to = "type",
    values_to = "deaths"
  )

ggplot(w2_worst, aes(x = mmwr_week, y = deaths, color = type, group = type)) +
  geom_line() +
  facet_wrap(~mmwr_year, scales = "free_y") +
  labs(
    title = "COVID Deaths vs Excess Deaths for SD in Wave 2",
    x = "MMWR Week",
    y = "Number of Deaths",
    color = "Type"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
#For wave 3 - State doing poorly - South Dakota

w3_worst <- dat2 |> 
  filter(state %in% c("FL")) |> 
  #wave 3: August-November 2021
  filter(date >= make_date(2021, 8, 1) & date <= make_date(2021, 12, 31)) |> 
  select(state, mmwr_year, mmwr_week, total_deaths, covid_deaths, excess_deaths) |>
  pivot_longer(
    cols = c(covid_deaths, excess_deaths),
    names_to = "type",
    values_to = "deaths"
  )

ggplot(w3_worst, aes(x = mmwr_week, y = deaths, color = type, group = type)) +
  geom_line() +
  facet_wrap(~mmwr_year, scales = "free_y") +
  labs(
    title = "COVID Deaths vs Excess Deaths for SD in Wave 2",
    x = "MMWR Week",
    y = "Number of Deaths",
    color = "Type"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}

w4_worst <- dat2 |> 
  filter(state %in% c("OK")) |> 
  #Wave 4: December 2021 - March 2022
  filter(date >= make_date(2021, 12, 1) & date <= make_date(2022, 3, 31)) |> 
  select(state, mmwr_year, mmwr_week, total_deaths, covid_deaths, excess_deaths) |>
  pivot_longer(
    cols = c(covid_deaths, excess_deaths),
    names_to = "type",
    values_to = "deaths"
  )

ggplot(w4_worst, aes(x = mmwr_week, y = deaths, color = type, group = type)) +
  geom_line() +
  facet_wrap(~mmwr_year, scales = "free_y") +
  labs(
    title = "COVID Deaths vs Excess Deaths for SD in Wave 2",
    x = "MMWR Week",
    y = "Number of Deaths",
    color = "Type"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
